services:
  web:
    build: .
    container_name: alk-web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      # Prisma будет брать DATABASE_URL отсюда
      DATABASE_URL: postgresql://alk:alk_password@db:5432/alk_db
    depends_on:
      - db
    # Чтобы изменения в коде сразу подхватывались (hot reload)
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "3000"]

  db:
    image: postgres:16
    container_name: alk-db
    environment:
      POSTGRES_USER: alk
      POSTGRES_PASSWORD: alk_password
      POSTGRES_DB: alk_db
    ports:
    - "5433:5432"
    volumes:
      - alk_db_data:/var/lib/postgresql/data

volumes:
  alk_db_data:
